# Continuous Delivery (CD):
#   Deploy release of the website.
name: cd-deploy-release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      version-tag:
        description: 'Existing Version Tag to Deploy (e.g. v1.0.0)'
        required: true

# Jobs.
jobs:
  # deploy to server via sftp, plus release notice.
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Display incoming workflow_dispatch inputs
        run: |
          echo "version-tag: ${{ github.event.inputs.version-tag }}"

      # Checks out your repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version-tag }}

      - name: Workaround to fix read only file issue
        run: chmod 644 ./Output/styles.css

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}             # This token is provided by Actions.
        with:
          tag_name: ${{ github.event.inputs.version-tag }}
          release_name: "Release ${{ github.event.inputs.version-tag }}"
          body_path: ./RELEASE_NOTES.md
          draft: false
          prerelease: false

      # Deploys via sftp to server.
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          sftp_only: true
          sftpArgs: '-o ConnectTimeout=5'
          delete_remote_files: false         # This is not working. Likely since no ssh access for this account.
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './Output/*'
          remote_path: './public_html'
