# Continuous Delivery (CD):
#   Deploy release of the website.
name: cd-deploy-release

# Controls when the workflow will run
on:
  # Triggers the workflow via a tag starting with 'v' (e.g. v2022.09.11.1411 ).
  push:
    tags:
      - v*

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Jobs.
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v3

      # Deploys via sftp to server.
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          sftp_only: false
          sftpArgs: '-o ConnectTimeout=5'
          delete_remote_files: false         # This is not working. Likely since no ssh access for this account.
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './Output/index.html'
          remote_path: './public_ftp'
