# Continuous Delivery (CD):
#   Generate release notes from the changelog.
name: cd-generate-releasenotes

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Jobs.
jobs:
  generate-releasenotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

#      - name: Extract release notes
#        id: releasenotes
#        uses: ffurrer2/extract-release-notes@v1
#        with:
#          changelog_file: ./CHANGELOG.md

      - name: Create release notes
        uses: CSchoel/release-notes-from-changelog@v1
        with:
          working-directory: ./

      # Overwrite as writing new release notes.
#      - name: Write to RELEASE_NOTES.md
#        uses: DamianReeves/write-file-action@master
#        with:
#          path: ./RELEASE_NOTES.md
#          contents: ${{ steps.releasenotes.outputs.release_notes }}
#          write-mode: overwrite

      - name: Commit and push RELEASE.md
        uses: EndBug/add-and-commit@v7
        with:
          add: RELEASE.md
          message: "chore: Update RELEASE.md"
