# This is a basic workflow to help you get started with Actions

name: cd_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs:
  # This workflow contains a single job.
  deployment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v3

      # Deploys via sftp to server.
      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'vraasnek'
          server: 'vraasnekkeri.com'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './Output/sitemap.xml'
          remote_path: '/home1/vraasnek/public_ftp'
          sftpArgs: '-o ConnectTimeout=5'
